<?php
defined('BASEPATH') or exit('No direct script access allowed');
class Payments extends CI_Controller
{
    public function __construct(){parent::__construct();$this->load->model('Payment_model','payments');}
    public function index(){ $status=strtoupper(trim((string)$this->input->get('status')));if(!in_array($status,['PENDING','APPROVED','REJECTED'],true))$status='';$data=['title'=>'Verifikasi Pembayaran','rows'=>$this->payments->confirmations($status?:null),'status'=>$status,'page_css'=>['admin.css']];$this->load->view('layout/header',$data);$this->load->view('layout/sidebar');$this->load->view('payments/index',$data);$this->load->view('layout/footer'); }
    public function approve($id){require_post();$ok=$this->payments->approve($id,current_user_id(),trim((string)$this->input->post('admin_note',true)));$this->session->set_flashdata($ok?'payments_ok':'payments_err',$ok?'Pembayaran berhasil diverifikasi.':'Pembayaran tidak dapat diverifikasi.');redirect('payments');}
    public function reject($id){require_post();$note=trim((string)$this->input->post('admin_note',true));if($note===''){$this->session->set_flashdata('payments_err','Alasan penolakan wajib diisi.');redirect('payments');}$ok=$this->payments->reject($id,current_user_id(),$note);$this->session->set_flashdata($ok?'payments_ok':'payments_err',$ok?'Bukti pembayaran ditolak.':'Data tidak dapat diproses.');redirect('payments');}
    public function methods(){require_owner();$data=['title'=>'Metode Pembayaran','rows'=>$this->payments->methods(),'page_css'=>['admin.css']];$this->load->view('layout/header',$data);$this->load->view('layout/sidebar');$this->load->view('payments/methods',$data);$this->load->view('layout/footer');}
    public function method_edit($id=0){require_owner();$row=$id?$this->payments->method($id):null;if($this->input->post()){ $data=['type'=>strtoupper(trim((string)$this->input->post('type',true)))?:'EWALLET','name'=>trim((string)$this->input->post('name',true)),'account_number'=>trim((string)$this->input->post('account_number',true)),'account_holder'=>trim((string)$this->input->post('account_holder',true)),'instructions'=>trim((string)$this->input->post('instructions',true))?:null,'is_active'=>$this->input->post('is_active')?1:0,'sort_order'=>(int)$this->input->post('sort_order'),'updated_at'=>date('Y-m-d H:i:s')];if($data['name']===''||$data['account_number']===''){$this->session->set_flashdata('payments_err','Nama dan nomor akun wajib diisi.');redirect($id?'payment-methods/edit/'.$id:'payment-methods/create');}$this->payments->save_method($id,$data);redirect('payment-methods'); }$data=['title'=>$id?'Edit Metode Pembayaran':'Tambah Metode Pembayaran','row'=>$row,'page_css'=>['admin.css']];$this->load->view('layout/header',$data);$this->load->view('layout/sidebar');$this->load->view('payments/method_form',$data);$this->load->view('layout/footer');}
}
